on:
  pull_request:
    branches: [ "demo", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4
     
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Launch build
        run: npm run build